# Pandas Intro

Pandas is a python library that helps you investigate and prep your data (e. g. cleaning, grouping, aggregating, plotting, joining). You can use it in Python notebooks like this one.

To install pandas:
`pip install pandas`

To run a notebook (Python must be downloaded on your computer):
In your terminal:
- Navigate to the folder that contains your file
- Run `jupyter notebook`

# Import Pandas

In [ ]:
import pandas as pd

# Loading Data

NYC Open Data 2018 Central Park Squirrel Census: https://data.cityofnewyork.us/Environment/2018-Central-Park-Squirrel-Census-Squirrel-Data/vfnx-vebw/data_preview

In [ ]:
# load the squirrels.csv file
squirrels_df = pd.read_csv('data/squirrels.csv')

Dataframes are 2D structures defined by rows and columns (like tables)

In [ ]:
# look at the first few rows
squirrels_df.head()

In [ ]:
# see all the columns
pd.set_option('display.max_columns', None)

# look at the last few rows
squirrels_df.tail()

In [ ]:
# seeing NaN in these columns:
# "Age", "Highlight Fur Color", "Color notes", "Specific Location", "Other Activities", "Other Interactions"

# clean up the data
squirrels_df.fillna("",inplace=True)

squirrels_df.head()

# Describing

In [ ]:
# rows?
len(squirrels_df)

In [ ]:
# columns
squirrels_df.columns

In [ ]:
# column data types
squirrels_df.dtypes

In [ ]:
# statistical summary of the numeric columns
squirrels_df.describe()

In [ ]:
# see most common values in a column of strings
squirrels_df['Primary Fur Color'].value_counts()

In [ ]:
# see breakdown of true/false for boolean columns
squirrels_df['Running'].value_counts(normalize=True)

# Finding and updating

In [ ]:
# locate a row, delete it
    #are there any rows with notes that we want to delete?
squirrels_df[squirrels_df['Color notes'] != ""]

In [ ]:
    # maybe get rid of "just outside hectare" row - this squirrel may not be accurately recorded.
    #location is 6
squirrels_df.iloc[6]

In [ ]:
#and drop it
squirrels_df.drop(index=6, inplace=True)

In [85]:
#check that it's gone
squirrels_df.iloc[4:8]

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,Combination of Primary and Highlight Color,Color notes,Location,Above Ground Sighter Measurement,Specific Location,Running,Chasing,Climbing,Eating,Foraging,Other Activities,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long,Action
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,Gray+Cinnamon,,Above Ground,,on tree stump,False,False,False,False,True,,False,False,False,False,False,False,False,False,,POINT (-73.9702676472613 40.7762126854894),Foraging
5,-73.968361,40.772591,11H-AM-1010-03,11H,AM,10102018,3,Adult,Cinnamon,White,Cinnamon+White,,,,,False,False,False,False,True,,False,False,False,False,True,False,True,False,,POINT (-73.9683613516225 40.7725908847499),Foraging
7,-73.958269,40.791737,33F-AM-1008-02,33F,AM,10082018,2,Adult,Gray,,Gray+,,Ground Plane,FALSE,,False,False,False,False,True,,False,False,False,False,False,False,True,False,,POINT (-73.9582694312289 40.7917367820255),Foraging
8,-73.967429,40.782972,21C-PM-1006-01,21C,PM,10062018,1,Adult,Gray,,Gray+,,Ground Plane,FALSE,,False,False,False,False,False,,False,False,False,True,True,False,False,False,,POINT (-73.9674285955293 40.7829723919744),

In [ ]:
# condense all of the boolean values into one "Action" column

#possible actions:
actions = ['Running', 'Chasing', 'Climbing', 'Eating', 'Foraging']
#if a squirrel has a "True" in action category, add that category to the "Action" column. If a squirrel has multiple "True" values, concatenate those categories together in the "Action" column.
def concatenate_actions(row):
    action_list = []
    for action in actions:
        if row[action] == True:
            action_list.append(action)
    return ", ".join(action_list)
squirrels_df['Action'] = squirrels_df.apply(concatenate_actions, axis=1)


squirrels_df.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,Combination of Primary and Highlight Color,Color notes,Location,Above Ground Sighter Measurement,Specific Location,Running,Chasing,Climbing,Eating,Foraging,Other Activities,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long,Action
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9561344937861 40.7940823884086),
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9688574691102 40.7837825208444),
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,,Gray,,Gray+,,Above Ground,10,,False,True,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.97428114848522 40.775533619083),Chasing
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,,Gray+,Nothing selected as Primary. Gray selected as ...,,,,False,False,False,True,True,,False,False,False,False,False,False,False,True,,POINT (-73.9596413903948 40.7903128889029),"Eating, Foraging"
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,Gray+Cinnamon,,Above Ground,,on tree stump,False,False,False,False,True,,False,False,False,False,False,False,False,False,,POINT (-73.9702676472613 40.7762126854894),Foraging

# Grouping

In [88]:
# aggregate by a column

#how many squirrels of each primary fur color are there, in AM vs PM?
squirrels_df.groupby(['Primary Fur Color', 'Shift']).size()

Primary Fur Color  Shift
                   AM         29
                   PM         26
Black              AM         51
                   PM         52
Cinnamon           AM        180
                   PM        212
Gray               AM       1086
                   PM       1386
dtype: int64

# Exporting

In [ ]:
# export to csv