# Pandas Intro

Pandas is a python library that helps you investigate and prep your data (e. g. cleaning, grouping, aggregating, plotting, joining). You can use it in Python notebooks like this one.

To install pandas:
`pip install pandas`

To run a notebook (Python must be downloaded on your computer):
In your terminal:
- Navigate to the folder that contains your file
- Run `jupyter notebook`

# Import Pandas

In [1]:
import pandas as pd

# Loading Data

NYC Open Data 2018 Central Park Squirrel Census: https://data.cityofnewyork.us/Environment/2018-Central-Park-Squirrel-Census-Squirrel-Data/vfnx-vebw/data_preview

In [2]:
# load the squirrels.csv file
squirrels_df = pd.read_csv('data/squirrels.csv')

Dataframes are 2D structures defined by rows and columns (like tables)

In [20]:
# look at the first few rows
squirrels_df.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,Combination of Primary and Highlight Color,Color notes,Location,Above Ground Sighter Measurement,Specific Location,Running,Chasing,Climbing,Eating,Foraging,Other Activities,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9561344937861 40.7940823884086)
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9688574691102 40.7837825208444)
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,,Gray,,Gray+,,Above Ground,10,,False,True,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.97428114848522 40.775533619083)
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,,Gray+,Nothing selected as Primary. Gray selected as ...,,,,False,False,False,True,True,,False,False,False,False,False,False,False,True,,POINT (-73.9596413903948 40.7903128889029)
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,Gray+Cinnamon,,Above Ground,,on tree stump,False,False,False,False,True,,False,False,False,False,False,False,False,False,,POINT (-73.9702676472613 40.7762126854894)

In [21]:
# see all the columns
pd.set_option('display.max_columns', None)

# look at the last few rows
squirrels_df.tail()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,Combination of Primary and Highlight Color,Color notes,Location,Above Ground Sighter Measurement,Specific Location,Running,Chasing,Climbing,Eating,Foraging,Other Activities,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Adult,Gray,,Gray+,,Ground Plane,FALSE,,False,False,False,True,True,,False,False,False,False,False,False,False,True,,POINT (-73.9639431360458 40.7908677445466)
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Adult,Gray,White,Gray+White,,Ground Plane,FALSE,,False,False,False,False,True,,False,False,False,False,False,False,True,False,,POINT (-73.9704015859639 40.7825600069973)
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,"Black, Cinnamon, White","Gray+Black, Cinnamon, White",,Ground Plane,FALSE,,False,False,False,True,True,,False,False,False,False,False,False,True,False,,POINT (-73.9665871993517 40.7836775064883)
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,,Gray,"Cinnamon, White","Gray+Cinnamon, White",,Ground Plane,FALSE,,False,False,False,True,False,,False,False,False,False,False,False,True,False,,POINT (-73.9639941227864 40.7899152327912)
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,Adult,Cinnamon,"Gray, White","Cinnamon+Gray, White",,Ground Plane,FALSE,,False,False,False,True,True,,False,False,False,False,False,True,False,False,,POINT (-73.9754794191553 40.7696404489025)

In [22]:
# seeing NaN in these columns:
# "Age", "Highlight Fur Color", "Color notes", "Specific Location", "Other Activities", "Other Interactions"

# clean up the data
squirrels_df.fillna("",inplace=True)

squirrels_df.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,Combination of Primary and Highlight Color,Color notes,Location,Above Ground Sighter Measurement,Specific Location,Running,Chasing,Climbing,Eating,Foraging,Other Activities,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9561344937861 40.7940823884086)
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9688574691102 40.7837825208444)
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,,Gray,,Gray+,,Above Ground,10,,False,True,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.97428114848522 40.775533619083)
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,,Gray+,Nothing selected as Primary. Gray selected as ...,,,,False,False,False,True,True,,False,False,False,False,False,False,False,True,,POINT (-73.9596413903948 40.7903128889029)
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,Gray+Cinnamon,,Above Ground,,on tree stump,False,False,False,False,True,,False,False,False,False,False,False,False,False,,POINT (-73.9702676472613 40.7762126854894)

# Describing

In [13]:
# rows?
len(squirrels_df)

3023

In [14]:
# columns
squirrels_df.columns

Index(['X', 'Y', 'Unique Squirrel ID', 'Hectare', 'Shift', 'Date',
       'Hectare Squirrel Number', 'Age', 'Primary Fur Color',
       'Highlight Fur Color', 'Combination of Primary and Highlight Color',
       'Color notes', 'Location', 'Above Ground Sighter Measurement',
       'Specific Location', 'Running', 'Chasing', 'Climbing', 'Eating',
       'Foraging', 'Other Activities', 'Kuks', 'Quaas', 'Moans', 'Tail flags',
       'Tail twitches', 'Approaches', 'Indifferent', 'Runs from',
       'Other Interactions', 'Lat/Long'],
      dtype='object')

In [16]:
# column data types
squirrels_df.dtypes

X                                             float64
Y                                             float64
Unique Squirrel ID                             object
Hectare                                        object
Shift                                          object
Date                                            int64
Hectare Squirrel Number                         int64
Age                                            object
Primary Fur Color                              object
Highlight Fur Color                            object
Combination of Primary and Highlight Color     object
Color notes                                    object
Location                                       object
Above Ground Sighter Measurement               object
Specific Location                              object
Running                                          bool
Chasing                                          bool
Climbing                                         bool
Eating                                           bool
Foraging                                         bool
Other Activities                               object
Kuks                                             bool
Quaas                                            bool
Moans                                            bool
Tail flags                                       bool
Tail twitches                                    bool
Approaches                                       bool
Indifferent                                      bool
Runs from                                        bool
Other Interactions                             object
Lat/Long                                       object
dtype: object

In [17]:
# statistical summary of the numeric columns
squirrels_df.describe()

                 X            Y          Date  Hectare Squirrel Number
count  3023.000000  3023.000000  3.023000e+03              3023.000000
mean    -73.967184    40.780853  1.011949e+07                 4.123718
std       0.007726     0.010285  4.246671e+04                 3.096492
min     -73.981159    40.764911  1.006202e+07                 1.000000
25%     -73.973102    40.771676  1.008202e+07                 2.000000
50%     -73.968594    40.778166  1.012202e+07                 3.000000
75%     -73.960189    40.791219  1.014202e+07                 6.000000
max     -73.949722    40.800119  1.020202e+07                23.000000

In [25]:
# see most common values in a column of strings
squirrels_df['Primary Fur Color'].value_counts()

Primary Fur Color
Gray        2473
Cinnamon     392
Black        103
              55
Name: count, dtype: int64

In [26]:
# see breakdown of true/false for boolean columns
squirrels_df['Running'].value_counts(normalize=True)

Running
False    0.758518
True     0.241482
Name: proportion, dtype: float64

# Finding and updating

In [ ]:
# locate a row, delete it

In [11]:
# condense all of the boolean values into one "Action" column?

# Grouping

In [4]:
# aggregate by a column
# find counts and averages?

# Exporting

In [7]:
# export to csv